name: Build and Push RagFlow Docker Images

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install uv
      run: |
        pip install uv
        
    - name: Download dependencies
      run: |
        uv run download_deps.py
        
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
      
    # 第一步：构建依赖镜像，但不推送到 Docker Hub
    - name: Build dependencies image
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./Dockerfile.deps
        push: false  # 不推送
        load: true   # 加载到本地 Docker 引擎
        platforms: linux/amd64
        tags: |
          infiniflow/ragflow_deps:latest
          
    # 第二步：构建主应用镜像
    - name: Build RagFlow slim image
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./Dockerfile
        push: false  # 不推送
        load: true   # 加载到本地 Docker 引擎
        platforms: linux/amd64
        build-args: |
          LIGHTEN=1
        tags: |
          infiniflow/ragflow:nightly-slim
          
    # 推送到私有仓库  
    - name: Login to private registry
      uses: docker/login-action@v2
      with:
        registry: registry.cn-beijing.aliyuncs.com
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
        
    - name: Tag and push to private registry
      if: success()
      run: |
        docker tag infiniflow/ragflow:nightly-slim registry.cn-beijing.aliyuncs.com/why_namespace/images:latest
        docker push registry.cn-beijing.aliyuncs.com/why_namespace/images:latest
